<?php
$this->headTitle('Sign in');

$form->get('username')->setAttributes([
    'class'=>'form-control mt-3', 
    'placeholder'=>'Courriel',
    'required' => true,
    'autofocus' => true
    ])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);

$form->get('password')->setAttributes([
    'class'=>'form-control mt-3', 
    'placeholder'=>'Mot de passe',
    'required' => true,
    ])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);
$form->get('submit')->setAttributes([
    'class' => 'btn btn-lg btn-primary btn-block mt-3'
])
?>

<div>
    <form class="form-signin mx-auto border rounded w-50 p-3 my-4" method="post">
        <h2 class="form-signin-heading">Connexion</h2>
        <?php if ($isLoginError): ?>
        <div class="alert alert-warning" role="alert">
            Mot de passe ou nom d'utilisateur incorrect
        </div>
        <?php endif; ?>
        <?= $this->formLabel($form->get('username')); ?>
        <?= $this->formElement($form->get('username')); ?>
        <?= $this->formLabel($form->get('password')); ?>
        <?= $this->formElement($form->get('password')); ?>
        <?= $this->formElement($form->get('redirect_url')); ?>
        <?= $this->formElement($form->get('csrf')) ?>
        <?= $this->formElement($form->get('submit')) ?>
    </form>
</div>