<header>
</header>

<main>
    <table class="datatable">
        <thead>
            <tr>
                <th>Auction</th>
                <th>Item</th>
                <th>Enchere</th>
                <th>Immédiat</th>
                <th>Quantité</th>
                <th>Temps</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($auctions as $a) : ?>
                <tr>
                    <td><?= $this->escapeHtml($a->_auc) ?></td>
                    <td><?= $this->escapeHtml($a->_item) ?></td>
                    <td><?= $this->escapeHtml($a->_bid) ?></td>
                    <td><?= $this->escapeHtml($a->_buyout) ?></td>
                    <td><?= $this->escapeHtml($a->_quantity) ?></td>
                    <td><?= $this->escapeHtml($a->_timeLeft) ?></td>
                    <td><a class="cursor-ptr" href="<?= $this->url('index',['action'=> 'edit','id' => $a->_auc]) ?>">Edit</a></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</main>